### PR TITLE
added a new dictionary and updated 5words.txt

### PR DESCRIPTION
**Pull request by mpa-LHutchinson**
This is for issue #3. I found a better dictionary in this github project: https://github.com/dwyl/english-words

I used the file "words_alpha.txt", it contains around 100k+ more words than the old dictionary. I also ran extract.py to update the file 5words.txt

### CODE REVIEW

**Comment by bodonovan** [comment]
Thanks for the quick fix

**Comment by mpa-LHutchinson** [comment]
@bodonovan can you add the "hacktoberfest-accepted" label to this pull request?

**Comment by bodonovan** [comment]
tag added

**Comment by mpa-LHutchinson** [comment]
@bodonovan I don't see a new label on this pull request, are you sure you added it?

**Comment by bodonovan** [comment]
I am fairly sure I added the label.

Not sure why you don't see it.

Are you not able too add it yourself?

**Comment by mpa-LHutchinson** [comment]
I don't see the label on this pull request. And I don't have permission to add it.

**Comment by bodonovan** [comment]
Do you see the label now?

**Comment by mpa-LHutchinson** [comment]
Yep! It went through to hacktoberfest. Thank you so much and I'd like to apologize for any confusion I caused.

**Pull request merged**
